#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "django-fmd"
name = "django-fmd"
description.en = "Web based FritzBox management using Python/Django."

version = "0.3.2~ynh1"

maintainers = ["Jens Diemer"]

[upstream]
license = "GPL-3.0"
website = "https://gitlab.com/jedie/django-find-my-device"
code = "https://gitlab.com/jedie/django-find-my-device"

[integration]
yunohost = ">= 4.4"
architectures = "all"
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/fmd"

    [install.admin]
    type = "user"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8000

    [resources.apt]
    packages = [
        "build-essential",
        "python3-dev",
        "python3-pip",
        "python3-venv",
        "git",
        "libpq-dev",
        "postgresql",
        "postgresql-contrib"
    ]

    [resources.database]
    type = "postgresql"
