#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "django-fmd"
name = "django-fmd"
description.en = "Web based FritzBox management using Python/Django."

version = "0.3.2~ynh2"

maintainers = ["Jens Diemer"]

[upstream]
license = "GPL-3.0"
website = "https://gitlab.com/jedie/django-find-my-device"
code = "https://gitlab.com/jedie/django-find-my-device"

[integration]
yunohost = ">= 11.2.12"
architectures = "all"
multi_instance = false
ldap = true
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/fmd"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8000

    [resources.apt]
    packages = [
        "build-essential",
        "python3-dev",
        "python3-pip",
        "python3-venv",
        "git",
        "libpq-dev",
        "postgresql",
        "postgresql-contrib"
    ]

    [resources.database]
    type = "postgresql"
