#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.default_from_email = "default_from_email@example.tld"
    args.admin_email = "admin_email@example.tld"

    # -------------------------------
    # Curl tests to validate that the app works
    # -------------------------------
    [default.curl_tests]

    # Sadly testing redirections to SSO is not possible yet,
    # Because "multisite" and "change_url" used other domains/subdomains
    # See: https://ci-apps-dev.yunohost.org/ci/job/14259

#    # Access the root page not logged in results in redirect to portal to login
#    home.path = "/"
#    home.logged_on_sso = false
#    home.expect_effective_url = "https://sub.domain.tld/yunohost/sso/?next=/"
#
#    # Access the Django Admin not logged in results in redirect to portal to login
#    admin.path = "/admin/"
#    admin.logged_on_sso = false
#    admin.expect_effective_url = "https://sub.domain.tld/yunohost/sso/?next=/admin/"

    # Access FMD web page as logged in user:
    home_logged_in.path = "/"
    home_logged_in.logged_on_sso = true
    home_logged_in.expect_title  = "Django Find My Device"
    home_logged_in.expect_content = "Go into Django Admin"
    home_logged_in.auto_test_assets = true

    # Access the Django Admin as logged in user:
    admin_logged_in.path = "/admin/"
    admin_logged_in.logged_on_sso = true
    admin_logged_in.expect_content = "Django Find My Device"
