#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

chmod o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE THE POSTGRES DATABASE
#=================================================
ynh_script_progression --message="Restoring the Postgresql database..." --weight=1

ynh_psql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" < ./db.sql

#=================================================
# PYTHON VIRTUALENV
#=================================================
ynh_script_progression --message="Update Python virtualenv..." --weight=5

python3 -m venv --upgrade --without-pip "$install_dir/venv"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="$app service" --log="/var/log/$app/$app.log"

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

ynh_restore_file --origin_path="/var/log/$app/"
chmod o-rwx "/var/log/$app"
chown -R "$app:" "/var/log/$app"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression --message="Reloading NGINX web server and $app's service..." --weight=1

ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Restoration completed for $app" --last
